ARG BASE=alpine:edge
FROM ${BASE}

RUN apk add --no-cache \
        openvpn \
        easy-rsa \
        bash \
        iptables \
        openssl \
        python3 \
 && { openvpn --version | grep -q '\[DCO\]' \
      || { echo "XATO: paketda DCO yo'q:"; openvpn --version | head -1; exit 1; }; }

COPY scripts/ /opt/vpn-scripts/
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /opt/vpn-scripts/*.py

EXPOSE 1194/udp

ENTRYPOINT ["/entrypoint.sh"]
